[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/sync-planning"
  status = 200
  to = "/.netlify/functions/sync-planning"

[[redirects]]
  force = true
  from = "/api/download-planning"
  status = 200
  to = "/.netlify/functions/download-planning"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
